README.md
docs/terraform.md
main.tf

Add a lifecycle rule to ignore changes to task-defintion
There is a known CD issue currently with Terraform and ECS - tracked in detail on this issue:
https://github.com/terraform-providers/terraform-provider-aws/issues/632
For now ignoring the task-definition changes will allow to make changes to other supporting modules (i.e. autoscaling) without rolling back the task definition to an older version. This is an example without the lifecycle rule, showing the sv-staging-data-model app being rolled back to an older image:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ module.data_model_web_app.module.autoscaling.aws_appautoscaling_target.default …
```

Add lifecycle rule to ignore task-definition changes

---

main.tf

- Enable resource-tagging for other taggeable resources.
- Resource tags are uniform across all resources provisioned by this module.
- More accurate observability when creating a resource group for said resources.

Add resource tags to other taggeable resources

---

README.md
docs/terraform.md
main.tf
variables.tf

Allows to add volume definitions to task like this
```
module "alb_service_task" {
source                    = "../terraform-aws-ecs-alb-service-task"
...
volumes = [
{
name = "${module.label_base.id}-data"
docker_volume_configuration = [
{
scope         = "shared"
autoprovision = true
},
]
},
]
}
```

Make volumes configurable

---

LICENSE
README.md
docs/terraform.md
main.tf
outputs.tf
variables.tf

* Fix name for `"aws_security_group" "ecs_service"`
* Wrong label was used for `name` in `"aws_security_group" "ecs_service"`. Since the default label was used without any additional attributes to disambiguate the names, when deploying the cluster, there were errors that a Security Group with the same name already existed. For the Security Group for the ECS service, should use the `service_label`

Fix name for `"aws_security_group" "ecs_service"`

---

README.md
docs/terraform.md
main.tf
variables.tf

Add `assign_public_ip` variable to allow configuring it. 
Rename variable `private_subnet_ids` to `subnet_ids` because it was misleading - public subnet ids can also be set here instead.
(Ref: https://www.terraform.io/docs/providers/aws/r/ecs_service.html#network_configuration-1)

feat: Allow configuration of auto assign public IP

---

README.md
docs/terraform.md
examples/complete/main.tf
outputs.tf

The task exec outputs are needed to add to the policy for SSM secrets usage and likely other things.

Add exec outputs

---

README.md
docs/terraform.md
main.tf
variables.tf

ECS Service supports a `deployment_controller` to enable support for CodeDeploy integration. This further enables the ability to use Blue/Green deployments via CodeDeploy.

Add deployment_controller option

---

main.tf

#28 added the controller to only one of the services. The service is duplicated so it isn't applying in all scenarios.
@aknysh @osterman

Add deployment_controller to ignored service

---

Makefile
README.md
docs/terraform.md
examples/complete/main.tf
main.tf
variables.tf

❗️❗️❗️❗️  Breaking Change ❗️❗️❗️❗️
As of AWS provider 2.22, multiple `load_balancer` configs are supported; see https://www.terraform.io/docs/providers/aws/r/ecs_service.html.
More details: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html.
We have a use case for using two target groups for a single service. AWS supports this, but this module limits it to 1.
For maximum compatibility, I added the ability to allow consumers to define their own ports, names, etc.

Add support for multiple load_balancer configs

---

README.md
docs/terraform.md
main.tf
variables.tf

Added missing configuration options/blocks that are available in terraform aws provider:
- `aws_ecs_service`
+ `placement_constraints`
+ `platform_version`
+ `service_registries`
+ `scheduling_strategy`
+ `ordered_placement_strategy`
- `aws_ecs_task_definition`
+ `placement_constraints`
+ `proxy_configuration`
Motivation: Allow to specify above arguments/blocks

feat: Add more configuration options from aws provider

---

README.md
docs/terraform.md
main.tf
variables.tf

This option is for the cases where ECS launch type is EC2 and the network mode is host and there is no alb fronting the application.
One could argue that this module has morf so much that the `alb` in the name might or might not need to be there

Adding the option to defina an empty ALB SGs

---

README.md
main.tf

This allows the ECS Service to create the log group so it does need to be created by the module user before hand.
Currently I add this permission to the ECS Exec Role *after* I invoke the module, so that it has this permission and I don't need to worry about creating that logs group for the service / task, but it would be nice to have that completely abstracted away from the module user.

Adds logs:CreateLogGroup to ECS Exec Role

---

README.md
docs/terraform.md
main.tf
variables.tf

If the old arn format is still used, then this module should not tag the service as that's not possible with the old arn.
Fixes https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/50
N/A

Use old arn format

---

main.tf

* Added description to the ICMP rule
* I spent a while trying to figure our why it was there
* describing SG rules is a best practice to help auditors 
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html#sg-rules-ping
* see `AWS018` in https://github.com/liamg/tfsec#included-checks

describe icmp rule

---

README.md
docs/terraform.md
main.tf
outputs.tf
variables.tf

* Add ability to override the task execution role arn as opposed to the module creating a default role
* The user may want to create the role outside of this module as the IAM profile may not fit their needs. For example using secretsmanager instead of ssm or wanting to restrict the container to specific secrets.
* closes #62

Task exec role arn

---

README.md
docs/terraform.md
main.tf
variables.tf

* Recently AWS announced support for EFS volumes in ECS fargate. This pull request adds those options to the task defenition.
* To reflect the current ecr task definition volume configuration options
* [ecs_task_definition.html#efs-volume-configuration-arguments](https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#efs-volume-configuration-arguments)
* [Amazon ECS and AWS Fargate support for Amazon EFS File Systems now generally available](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/)

Added EFS volume config to ECR fargate task definition

---

README.md
README.yaml
docs/terraform.md
main.tf
variables.tf

Nothing too exciting here: bump the label module to the latest and allow the `environment` to be set; add $self to contributors.

Bump label to 0.16.0; allow `environment` to be set

---

README.md
main.tf

* Allow ECS services to register and deregister targets on a Target Group
* To support the use of ALBs
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/65

Adding target group permissions needed for ALB support

---

README.md
README.yaml
docs/terraform.md
variables.tf

Description of `container_definition_json` is somewhat obscure regarding the possibility to use multiple container definitions. This MR addresses #69 by making this ability more explicit.
- Closes #69

Document multi-container task definitions in container_definition_json

---

README.md
docs/terraform.md
main.tf
variables.tf

* Allow all egress security group rule to be optional (Default to enabled for backwards compatibility)
* Security and compliance rules means we cannot simply allow everything egress
* Need to be able define the egress rules ourselves

Make adding all egress rule to the ECS security group optional

---

main.tf

* Look up the authorization_config settings under efs_volume_config instead of volume 
* Because it can't find authorization_config anywhere else.
* closes #74

Lookup authorization_config under efs_volume_config

---

README.md
docs/terraform.md
examples/complete/versions.tf
versions.tf

* Update to accept 0.13 and aws provider 3
* To make provider versions compatible

Update provider pinning

---

context.tf
examples/complete/context.tf
main.tf

- Update `terraform-null-label` to restore attribute order handling in place prior to #82
- Automatic merging of old attributes with new attributes was added to `terraform-null-label` v0.19.0 and incorporated into this module in #82. However, prior to `terraform-null-label` v0.22.1, it placed new attributes in front of old attributes, instead of the previous behavior of this module, which was to place new attributes at the end of the attribute list. This causes unnecessary and unwanted changes in resource names.
-  cloudposse/terraform-null-label#113

Update null-label to restore attribute order

---

README.md
docs/terraform.md
outputs.tf

* Expose ARN for service so we don't have to manually construct it
* Ease of use and preventing user error

Expose ARN for service so we don't have to manually construct it

---

README.md
README.yaml
docs/terraform.md

Fixed the HCL spacing in the `README.md` example
Because it was annoying to fix the spacing when copying and pasting
N/A

Fix HCL spacing in example

---

README.md
docs/terraform.md
variables.tf

* `var.subnet_ids` should be optional
* It's only required if `awsvpc` is the `launch_type` since it's only used for `aws_ecs_service`'s `network_configuration`
* This makes it easier for EC2 (non fargate) tasks
N/A

var.subnet_ids should be optional

---

README.md
docs/terraform.md
variables.tf

* Set enable_icmp_rule default to false
* It doesn't make sense to me why icmp is enabled by default. It should be enabled if it's needed. I have to explicitly disable this one each service.
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/105

Set enable_icmp_rule default to false

---

main.tf

* Only create the sg if network_mode == awsvpc
* Looks like the security group is used only if var.network_mode = "awsvpc"
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/102

Only create the sg if network_mode == awsvpc

---

main.tf

* Add name_prefix and lifecycle to sg
* Name changes to the security group may not be able to be destroyed easily. 
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/77
Unsure if both the lifecycle and the `name_prefix` args need to be set. Might be good enough just to do the lifecycle.
I'm thinking it might be better to remove the `name_prefix` and see if the lifecycle clears the issue for the user.

Add create_before_destroy lifecycle to sg

---

README.md
docs/terraform.md
versions.tf

I removed the template provider
It is not used anywhere and the provider itself is  deprecated and without a darwin arm64 release, making it unusable for new macbook users.

remove unused provider

---

README.md
docs/terraform.md
main.tf
outputs.tf
variables.tf

* Add `ignore_desired_count` aws_ecs_service that has lifecycle setup to ignore `desired_count` changes
* Desired count is a rough estimate that can be volatile during peak hours of the service that the containers serve
* Autoscaling policies may have scaled the number of tasks to above/below the desired count, so on a deployment of a new feature/change we don't want the desired count to be reset
* No GitHub Issue for this as far as I'm aware

Add ECS Service with ignore desired_count

---

README.md
outputs.tf

*  Add empty string to the try function in service_name and service_arn outputs.
*  Prevent error when module `enabled` is set to `false`.

Add empty string to outputs

---

README.md
docs/terraform.md
main.tf
variables.tf

* Adds `var.ephemeral_storage_size` + usage within the task definition
* Enables Fargate tasks to increase the size of their ephemeral storage
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#ephemeral_storage
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_EphemeralStorage.html

feat: adds ephemeral_storage_size var for Fargate

---

main.tf

* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/155 was meant/stated to fix https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/136, but the PR didn't actually change the line that was causing the issue
* This PR makes the necessary change to fix the issue, which is to change the conditional for determining whether to create an IAM role for the ECS service that this module provisions: don't create the role if `var.ecs_load_balancers` is empty; otherwise, create it
* The IAM role is assigned a policy that allows it to call load balancer APIs, which isn't necessary if no load balancing is needed
* Trying to attach the role to the ECS service anyways with network mode set to bridge results in an error as noted by #136
Previous PRs
* …

Don't create IAM role for the service if there are no load balancers

---

.github/auto-release.yml
README.md
docs/terraform.md
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

* Add ecs_service_enabled
* Create all the underlying resources but skip the ecs service. This is useful when creating a run-once task such as for db migrations.
N/A

Add ecs_service_enabled

---

main.tf
outputs.tf

* task role uses for each
* fixes: #167 
The outputs had to be changed to output a map as a single string, hence why they look complex, it's to keep backwards compatibility

Task Role uses for-each instead of count

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/auto-context.yml
.github/workflows/auto-format.yml
.github/workflows/auto-readme.yml
.github/workflows/auto-release.yml
.github/workflows/chatops.yml
.github/workflows/validate-codeowners.yml
README.md
docs/terraform.md
examples/complete/fixtures.us-east-2.tfvars
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

* Adds a variable to enable/disable triggering a new ECS service deployment on apply.
* In aws provider [v4.40.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.40.0) an option was added to allow triggering a new ECS service deployment on apply.
* This is useful so the service can be updated to the latest service/task configuration without needing to take additional steps are applying the Terraform config.
* None

Add option to trigger a redeployment on apply

---

README.md
docs/terraform.md
outputs.tf
versions.tf

* Add `task_definition_arn_without_revision` output, using the [`arn_without_revision`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#arn_without_revision) attribute from `aws_ecs_task_definition` resource.
* Update minimum AWS provider version to `v4.59.0`.
* Useful for situations where the latest task definition is always desired.
* Avoiding manual string manipulation to strip the revision from the ARN.
* Added to AWS provider in version `v4.59.0`: https://github.com/hashicorp/terraform-provider-aws/issues/27119

feat: Add task_definition_arn_without_revision output

---

README.md
docs/terraform.md
main.tf
variables.tf
versions.tf

- Adds [track_latest](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#track_latest) and bumps provider version to [v5.37.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.37.0) accordingly.
- Allow users to make the task definitions track always the latest one if track_latest is set to true.
- Closes https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/issues/221
- See original addition of this argument to the provider here: https://github.com/hashicorp/terraform-provider-aws/pull/30154

feat: adds support for track_latest

---

test/src/examples_complete_test.go

```console
Error:     Not equal: 
expected: "arn:aws:ecs:us-east-2:126450723953:cluster/eg-test-ecs-alb-service-task-ezatqz"
actual  : "arn:aws:ecs:us-east-2:799847381734:cluster/eg-test-ecs-alb-service-task-ezatqz"
```
- Terratests are failing due to assertions not validating with the expected account ID
- [Failing Job](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/actions/runs/11236371502/job/31236371170)

fix: update Terratest assertions with AWS account
